### PR TITLE
Fix parsing API parameters without type

### PR DESCRIPTION
**Pull request by aszlig**
If there is no specific type specified for an `@apiParam`, the parsing fails because it tries to find '=' within the type variable and if it is `None`, it can't iterate to find the equals sign.

So whenever the `type_` group from the regex now is `None`, we just set the parsed type to `None` and also make sure we handle this properly when rendering the docstring.

In more recent versions of Habitica the following `@apiParam` was introduced, which exactly triggers this problem:

```
@apiParam (Query) [dueDate] type Optional date to use for computing the nextDue field for each returned task.
```

### CODE REVIEW

**Comment by ASMfreaK** [comment]
Hi! It looks good to me, but can you please add the offending apidoc to [tests](https://github.com/ASMfreaK/habitipy/blob/master/tests/test_api.py), so we'll make sure not to induce regression on this issue in the future versions?

**Comment by ASMfreaK** [comment]
Thanks!

**Comment by ASMfreaK** [comment]
I have uploaded the fix to pypi

**Comment by aszlig** [comment]
@ASMfreaK: Ah, thanks and sorry for not getting back to adding the test case.

**Pull request merged**
